window.MOE_PLATFORM_DATA = {
  features: [
    ["stance_x", "球员横向站位"],
    ["stance_y", "球员纵向站位"],
    ["swing_speed", "挥拍速度"],
    ["ball_speed", "球速"],
    ["landing_x", "落点横向区域"],
    ["landing_y", "落点纵向区域"],
    ["angle", "击球角度"],
    ["height", "击球高度"],
  ],
  labels: ["正手抽球", "反手削球", "网前吊球", "高压球"],
  runs: [
    {
      id: "final_dense_mlp",
      name: "Dense MLP",
      bestEpoch: 63,
      params: 12004,
      activeParams: 12004,
      testLoss: 0.000373,
      accuracy: 1,
      macroF1: 1,
      balancedAccuracy: 1,
      cvLoad: null,
      maxMean: null,
      gateEntropy: null,
    },
    {
      id: "final_moe_k1_lb",
      name: "MoE-K=1, lb=0.01",
      k: 1,
      lambdaLb: 0.01,
      bestEpoch: 42,
      params: 20596,
      activeParams: 7336,
      testLoss: 0.011049,
      accuracy: 1,
      macroF1: 1,
      balancedAccuracy: 1,
      cvLoad: 0.174105,
      maxMean: 1.125,
      gateEntropy: 1.38379,
    },
    {
      id: "final_moe_k2_lb",
      name: "MoE-K=2, lb=0.01",
      k: 2,
      lambdaLb: 0.01,
      bestEpoch: 67,
      params: 20596,
      activeParams: 11756,
      testLoss: 0.010445,
      accuracy: 1,
      macroF1: 1,
      balancedAccuracy: 1,
      cvLoad: 0.16322,
      maxMean: 1.2375,
      gateEntropy: 0.374603,
    },
    {
      id: "final_moe_k1_no_lb",
      name: "MoE-K=1, lb=0",
      k: 1,
      lambdaLb: 0,
      bestEpoch: 83,
      params: 20596,
      activeParams: 7336,
      testLoss: 0.000274,
      accuracy: 1,
      macroF1: 1,
      balancedAccuracy: 1,
      cvLoad: 0.776812,
      maxMean: 2.15,
      gateEntropy: 1.359131,
    },
    {
      id: "final_moe_k2_no_lb",
      name: "MoE-K=2, lb=0",
      k: 2,
      lambdaLb: 0,
      bestEpoch: 67,
      params: 20596,
      activeParams: 11756,
      testLoss: 0.000204,
      accuracy: 1,
      macroF1: 1,
      balancedAccuracy: 1,
      cvLoad: 0.339692,
      maxMean: 1.5875,
      gateEntropy: 0.384336,
    },
  ],
  routing: {
    k1: {
      title: "K=1 selected gate 权重热图",
      image: "../runs/final_moe_k1_lb/figures/mean_selected_gate_by_class_heatmap.png",
      matrix: [
        [0.075, 0.15, 0, 0.775],
        [0.05, 0.5, 0.325, 0.125],
        [0.15, 0.05, 0.8, 0],
        [0.8, 0, 0, 0.2],
      ],
    },
    k2: {
      title: "K=2 selected gate 权重热图",
      image: "../runs/final_moe_k2_lb/figures/mean_selected_gate_by_class_heatmap.png",
      matrix: [
        [0.022614, 0.028543, 0.00294, 0.945903],
        [0.016877, 0.014024, 0.961048, 0.00805],
        [0.957692, 0, 0.034948, 0.00736],
        [0, 0.967873, 0.014709, 0.017418],
      ],
    },
  },
  figures: {
    "K=1 MoE": [
      ["专家分工", "../runs/final_moe_k1_lb/figures/mean_selected_gate_by_class_heatmap.png"],
      ["混淆矩阵", "../runs/final_moe_k1_lb/figures/confusion_matrix_normalized.png"],
      ["训练曲线", "../runs/final_moe_k1_lb/figures/training_curves.png"],
      ["专家纯度", "../runs/final_moe_k1_lb/figures/expert_to_class_heatmap.png"],
    ],
    "K=2 MoE": [
      ["专家分工", "../runs/final_moe_k2_lb/figures/mean_selected_gate_by_class_heatmap.png"],
      ["混淆矩阵", "../runs/final_moe_k2_lb/figures/confusion_matrix_normalized.png"],
      ["训练曲线", "../runs/final_moe_k2_lb/figures/training_curves.png"],
      ["专家纯度", "../runs/final_moe_k2_lb/figures/expert_to_class_heatmap.png"],
    ],
    "MLP Baseline": [
      ["混淆矩阵", "../runs/final_dense_mlp/figures/confusion_matrix_normalized.png"],
      ["训练曲线", "../runs/final_dense_mlp/figures/training_curves.png"],
    ],
  },
  publicTest: {
    sourceName: "Kaggle PKLMart Competitive Pickleball Extracts",
    sourceUrl: "https://www.kaggle.com/datasets/cakesofspan/pklmarts-competitive-pickleball-extracts/data",
    dataUrl: "Kaggle downloaded archive.zip",
    method: "scikit-learn Pipeline",
    datasetShape: [32000, 16],
    split: { train: 22280, val: 3104, test: 6616 },
    splitMethod: "GroupShuffleSplit(match_id)",
    labels: ["3rd Shot Drive", "3rd Shot Drop", "Dink", "Hand Battle"],
    results: [
      { model: "Logistic Regression", accuracy: 0.7, macroF1: 0.6991, balancedAccuracy: 0.6996 },
      { model: "Random Forest", accuracy: 0.74, macroF1: 0.7389, balancedAccuracy: 0.7388 },
    ],
    figures: [
      ["LogReg 混淆矩阵", "../public_data_test/pklmart_pickleball/figures/logreg_confusion_matrix.png"],
      ["Random Forest 混淆矩阵", "../public_data_test/pklmart_pickleball/figures/rf_confusion_matrix.png"],
    ],
  },
};
